# Generated by Django 4.2.7 on 2023-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.TextField(max_length=266),
        ),
    ]
